### ISSUE TITLE
Discord Canary & PTB Webhooks aren't recognized

### ISSUE THREAD

**Issue by ternera** [ni5arga/Modmail-To-Discord-Slack#1]
I noticed that you only check for Discord webhooks that start with "https://discord.com/api/webhooks/", but it may be helpful to add another if statement to check for webhooks that start with "https://canary.discord.com/api/webhooks/" and "https://ptb.discord.com/api/webhooks/". I use the Discord canary client, so this threw me off when nothing was being sent to the webhook.

**Comment by ni5arga** [comment]
Thanks for reporting! Will fix it in the next update.

**Comment by ni5arga** [comment]
```
[ERROR] Jan 26 15:13:25 Error: HTTP request to domain: canary.discord.com is not allowed
```
Hey - looks like the admins haven't approved the domain yet, I'll let them know.

**Comment by ni5arga** [comment]
Fixed it in [this commit](https://github.com/ni5arga/Modmail-To-Discord-Slack/commit/c515a0c6f04d9ebbf1d30cfc385fab680ff7ca5f).
